n = input('Digite seu nome completo: ').strip()
n1 = n.split()
n2 = ''.join(n1)
print('Analisando seu nome...')
print(f'Seu nome em maiuscuslas é {n.upper()}')
print(f'Seu nome em minusculas é {n.lower()}')
print(f'Seu nome ao todo tem {len(n2)} letras')
print(f'Seu primeiro nome é {n1[0]} e ele tem {len(n1[0])} letras')
print(n2)
